services:
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
      target: dev
    container_name: handly-client
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/client/node_modules
    depends_on:
      - server
    init: true
    restart: unless-stopped
