services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
      target: dev
    container_name: handly-server
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/server/node_modules
    depends_on:
      redis:
        condition: service_healthy
    init: true
    restart: unless-stopped
